# Generated by Django 3.2.7 on 2022-04-07 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='userAction',
            field=models.CharField(max_length=5000000, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='userAgent',
            field=models.CharField(max_length=5000000, null=True),
        ),
        migrations.AddField(
            model_name='responseblock',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='responseblock',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
