# Generated by Django 3.2.7 on 2022-04-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0004_response_respondent_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
