# Generated by Django 3.2.7 on 2022-04-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0004_response_respondent_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseblock',
            name='gazeData',
            field=models.CharField(max_length=5000000, null=True),
        ),
    ]
