# Generated by Django 3.2.7 on 2022-04-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0005_response_preview'),
        ('surveytaker', '0005_responseblock_gazedata'),
    ]

    operations = [
    ]
