# Generated by Django 3.2.7 on 2022-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0005_response_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completion_rate',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
