# Generated by Django 3.2.7 on 2022-04-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0006_merge_20220427_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseblock',
            name='clickEvent',
            field=models.CharField(max_length=5000000, null=True),
        ),
    ]
