# Generated by Django 3.2.7 on 2022-04-29 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0007_responseblock_clickevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseblock',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='responseblock',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
