# Generated by Django 3.2.7 on 2022-05-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0007_remove_response_completion_rate'),
        ('surveytaker', '0008_auto_20220429_1433'),
    ]

    operations = [
    ]
