# Generated by Django 3.2.7 on 2022-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0010_auto_20220506_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='camera_state',
            field=models.BooleanField(default=True),
        ),
    ]
