# Generated by Django 3.2.7 on 2023-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0012_auto_20230422_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='calibration_acc',
            field=models.IntegerField(default=0),
        ),
    ]
