# Generated by Django 3.2.7 on 2023-05-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveytaker', '0013_alter_response_calibration_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='questionsOrder',
            field=models.CharField(max_length=5000000, null=True),
        ),
    ]
