# Generated by Django 3.2.7 on 2022-03-23 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=15000)),
                ('title', models.CharField(blank=True, default='', max_length=5000)),
                ('order', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=5000)),
                ('type', models.CharField(blank=True, default='', max_length=5000)),
                ('description', models.CharField(blank=True, default='', max_length=5000)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=None)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.block')),
            ],
        ),
        migrations.CreateModel(
            name='TextboxQuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, default='', max_length=5000)),
                ('validate', models.BooleanField(default=False)),
                ('textboxMax', models.IntegerField(default=0)),
                ('textboxMin', models.IntegerField(default=0)),
                ('ansType', models.CharField(blank=True, default='Text', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=5000)),
                ('language', models.CharField(blank=True, default='', max_length=5000)),
                ('consentText', models.CharField(blank=True, default='', max_length=10000)),
                ('current_submission', models.IntegerField(default=0)),
                ('required_submission', models.IntegerField(default=0)),
                ('time_limit_minutes', models.IntegerField(default=60)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('publish_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('expire_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_repeat_answer', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, default='', max_length=5000)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPostQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleURL', models.URLField(blank=True, default='', max_length=5000)),
                ('articleTitle', models.CharField(blank=True, default='', max_length=5000)),
                ('articleSource', models.CharField(blank=True, default='', max_length=5000)),
                ('articleImageLink', models.CharField(blank=True, default='', max_length=5000)),
                ('articleStyle', models.CharField(blank=True, default='Twitter', max_length=5000)),
                ('articleSnippet', models.CharField(blank=True, default='', max_length=5000)),
                ('articleLikes', models.IntegerField(default=0)),
                ('articleComments', models.IntegerField(default=0)),
                ('articleShares', models.IntegerField(default=0)),
                ('articleCommentsOn', models.BooleanField(default=False)),
                ('articleSharesOn', models.BooleanField(default=False)),
                ('articleLikesOn', models.BooleanField(default=False)),
                ('numberAddon', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='Randomiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subset', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveybuilder.survey')),
            ],
        ),
        migrations.CreateModel(
            name='PostAddonfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=5000)),
                ('icon', models.CharField(blank=True, default='', max_length=5000)),
                ('count', models.IntegerField(default=0)),
                ('postRow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.socialpostquestion')),
            ],
        ),
        migrations.CreateModel(
            name='NumberScaleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minTitle', models.CharField(blank=True, default='', max_length=5000)),
                ('middleTitle', models.CharField(blank=True, default='', max_length=5000)),
                ('maxTitle', models.CharField(blank=True, default='', max_length=5000)),
                ('interval', models.IntegerField(default=0)),
                ('numberMax', models.IntegerField(default=0)),
                ('numberMin', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(default=0)),
                ('isDropDown', models.BooleanField(default=False)),
                ('isCheckbox', models.BooleanField(default=False)),
                ('textboxMax', models.IntegerField(default=1)),
                ('textboxMin', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, default='', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.multichoicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDropQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.IntegerField(default=0)),
                ('cards', models.IntegerField(default=0)),
                ('textboxMax', models.IntegerField(default=1)),
                ('textboxMin', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDropChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, default='', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.draganddropquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DragAndDropCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, default='', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.draganddropquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonRowQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberButtons', models.IntegerField(default=0)),
                ('goToEnd', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttonText', models.CharField(blank=True, default='', max_length=5000)),
                ('buttonType', models.CharField(blank=True, default='', max_length=5000)),
                ('buttonIcon', models.CharField(blank=True, default='', max_length=5000)),
                ('answered', models.BooleanField(default=False)),
                ('goToEnd', models.BooleanField(default=False)),
                ('buttonRow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.buttonrowquestion')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='randomiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveybuilder.randomiser'),
        ),
        migrations.AddField(
            model_name='block',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.survey'),
        ),
    ]
