# Generated by Django 3.2.7 on 2022-04-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0003_auto_20220331_1713'),
        ('surveybuilder', '0003_auto_20220331_1744'),
    ]

    operations = [
    ]
