# Generated by Django 3.2.7 on 2022-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0004_merge_0003_auto_20220331_1713_0003_auto_20220331_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='if_capture_gaze',
            field=models.BooleanField(default=True),
        ),
    ]
