# Generated by Django 3.2.7 on 2022-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0005_survey_if_capture_gaze'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
