# Generated by Django 3.2.7 on 2022-05-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0005_survey_duration'),
        ('surveybuilder', '0005_survey_if_capture_gaze'),
    ]

    operations = [
    ]
