# Generated by Django 3.2.7 on 2022-05-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0006_merge_20220502_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='if_capture_gaze',
        ),
        migrations.AlterField(
            model_name='survey',
            name='duration',
            field=models.IntegerField(default=-1),
        ),
    ]
