# Generated by Django 3.2.7 on 2022-05-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0006_alter_survey_if_capture_gaze'),
        ('surveybuilder', '0008_survey_if_capture_gaze'),
    ]

    operations = [
    ]
