# Generated by Django 3.2.7 on 2022-05-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0006_question_image'),
        ('surveybuilder', '0009_merge_20220506_1254'),
    ]

    operations = [
    ]
