# Generated by Django 3.2.7 on 2022-05-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0010_merge_0006_question_image_0009_merge_20220506_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicequestion',
            name='otherInput',
            field=models.BooleanField(default=False),
        ),
    ]
