# Generated by Django 3.2.7 on 2022-05-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0011_multichoicequestion_otherinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
