# Generated by Django 3.2.7 on 2022-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0012_survey_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='camera',
            field=models.BooleanField(default=False),
        ),
    ]
