# Generated by Django 3.2.7 on 2022-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0017_auto_20220922_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixtablequestion',
            name='tableConfig',
            field=models.TextField(blank=True, default='[{"name":"Default1"},{"name":"Default2"},{"name":"Default3"}]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='matrixtablequestion',
            name='columnConfig',
            field=models.TextField(blank=True, default='[{"label":"Strong disagree","value":"e"},{"label":"Disgree","value":"d"},{"label":"Neutral","value":"c"},{"label":"Agree","value":"b"},{"label":"Strong agree","value":"a"}]', max_length=5000),
        ),
    ]
