# Generated by Django 3.2.7 on 2022-09-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0020_alter_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
