# Generated by Django 3.2.7 on 2022-09-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0021_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidersQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(default=0)),
                ('isDropDown', models.BooleanField(default=False)),
                ('isCheckbox', models.BooleanField(default=False)),
                ('textboxMax', models.IntegerField(default=1)),
                ('textboxMin', models.IntegerField(default=1)),
                ('multipleAnswers', models.BooleanField(default=False)),
                ('otherInput', models.BooleanField(default=False)),
                ('columnConfig', models.TextField(blank=True, default='[{"label":"非常不满意","value":"e"},{"label":"不满意","value":"d"},{"label":"可以接受","value":"c"},{"label":"满意","value":"b"},{"label":"非常满意","value":"a"}]', max_length=5000)),
                ('tableConfig', models.TextField(blank=True, default='[{"name":"服务"},{"name":"环境"},{"name":"价格"}]', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, default='', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.slidersquestion')),
            ],
        ),
    ]
