# Generated by Django 3.2.7 on 2022-09-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0022_sliders_slidersquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersquestion',
            name='Grid',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='slidersquestion',
            name='max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='slidersquestion',
            name='min',
            field=models.IntegerField(default=1),
        ),
    ]
