# Generated by Django 3.2.7 on 2022-09-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0023_auto_20220930_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidersquestion',
            old_name='Grid',
            new_name='grid',
        ),
    ]
