# Generated by Django 3.2.7 on 2022-09-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0024_rename_grid_slidersquestion_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersquestion',
            name='columnConfig',
            field=models.TextField(blank=True, default='[{"label":"Label1","value":"e"},{"label":"Label2","value":"d"},{"label":"Label3","value":"c"},{"label":"Label4","value":"b"}]', max_length=5000),
        ),
        migrations.AlterField(
            model_name='slidersquestion',
            name='min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slidersquestion',
            name='tableConfig',
            field=models.TextField(blank=True, default='[{"name":"Choice1"},{"name":"Choice2"},{"name":"Choice3"}]', max_length=5000),
        ),
    ]
