# Generated by Django 3.2.7 on 2022-09-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0025_auto_20220930_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(default=0)),
                ('isDropDown', models.BooleanField(default=False)),
                ('isCheckbox', models.BooleanField(default=False)),
                ('textboxMax', models.IntegerField(default=1)),
                ('textboxMin', models.IntegerField(default=1)),
                ('multipleAnswers', models.BooleanField(default=False)),
                ('otherInput', models.BooleanField(default=False)),
                ('columnConfig', models.TextField(blank=True, default='[{"label":"Label1","value":"e"},{"label":"Label2","value":"d"},{"label":"Label3","value":"c"},{"label":"Label4","value":"b"}]', max_length=5000)),
                ('tableConfig', models.TextField(blank=True, default='[{"name":"Choice1"},{"name":"Choice2"},{"name":"Choice3"}]', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.question')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, default='', max_length=5000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveybuilder.groupsquestion')),
            ],
        ),
    ]
