# Generated by Django 3.2.7 on 2022-10-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0026_groups_groupsquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='groupsquestion',
            name='columnConfig',
            field=models.TextField(blank=True, default='[{"label":"Label1","value":"e","children":[]},{"label":"Label2","value":"d","children":[]}]', max_length=5000),
        ),
    ]
