# Generated by Django 3.2.7 on 2022-10-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0027_auto_20221019_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=5000)),
                ('user', models.CharField(blank=True, default='', max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='avatarUrl',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
