# Generated by Django 3.2.7 on 2022-10-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0028_auto_20221019_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avatarUrl',
            field=models.CharField(blank=True, default='/upload/0.5635229252972436WeChat0f76336fb69d8e174d7d6ad50cc53a5d.png', max_length=5000),
        ),
    ]
