# Generated by Django 3.2.7 on 2023-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0031_alter_matrixtablequestion_columnconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostquestion',
            name='articleRetweets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpostquestion',
            name='articleRetweetsOn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpostquestion',
            name='articleSends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialpostquestion',
            name='articleSendsOn',
            field=models.BooleanField(default=False),
        ),
    ]
