# Generated by Django 3.2.7 on 2023-09-10 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0032_auto_20230525_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='collaborator',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]