# Generated by Django 3.2.7 on 2024-05-03 01:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveybuilder', '0033_survey_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='collaborator',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
